all:    _naichichi2_client
server: _naichichi2_server

_naichichi2_client:
	make -f Makefile.naichichi2_client

_naichichi2_server:
	make -f Makefile.naichichi2_server

clean:
	/bin/rm *.o *.bak *~ core
	/bin/rm naichichi2 naichichi2_client naichichi2_server naichichi2_debug
